spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_element_admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 3flreaem37
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      enabled: true
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 7999
logging:
  path: /home/vue-element-admin/logs